name: Build and Deploy Schedule Services API.

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
       - main
    types: [ opened, synchronized, reopened ]

  workflow_dispatch:
    inputs:
      version:
        default: 1.0.0
        description: Version number of dependency
        required: true

env:
  APPLICATION_NAME: CCI_ApigeeInterface
  APPLICATION_ARTIFACTID: CCI_ApigeeInterface
  APPLICATION_VERSION: 0.0.1-SNAPSHOT
  JFROG_URL: https://packages.aa.com/artifactory
  JFROG_CLI_HOME_DIR: ${{ github.workspace }}/.jfrog
  JFROG_CLI_JCENTER_REMOTE_SERVER: Default-Server
  JFROG_CLI_JCENTER_REMOTE_REPO: Jcenter.bintray-proxy
  JFROG_CLI_OFFER_CONFIG: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3

    - name: Set Maven Home Variable
      run: |
         echo "M2_HOME=`mvn --version | grep -i "MAVEN HOME" | awk -F': ' '{print $NF}'`" >> $GITHUB_ENV
         echo "${{ env.M2_HOME }}"
           
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1.1.0
      with:
        # Optional: JFrog CLI Version, default is 1.40.0
        version: 1.37.1 

    - name: Configure JFrog CLI
      run: |
        mvn --version
        jfrog rt config --url=$JFROG_URL --user=${{ secrets.ARTIFACTORY_CRED_USR }} --access-token=${{ secrets.ARTIFACTORY_CRED_PAT }} --interactive=false
        jfrog rt c show
        jfrog rt mvnc --server-id-resolve=Default-Server --server-id-deploy=Default-Server --repo-resolve-releases=maven-public --repo-resolve-snapshots=OT-snapshots --repo-deploy-releases=dev-releases --repo-deploy-snapshots=snapshots
      env:
        JFROG_URL: https://packages.aa.com/artifactory
        JFROG_CLI_JCENTER_REMOTE_SERVER: Default-Server
        JFROG_CLI_JCENTER_REMOTE_REPO: Jcenter.bintray-proxy
        JFROG_CLI_OFFER_CONFIG: false
  
    - name: Build, Test, and Scan
      run: |
        cat $GITHUB_WORKSPACE/settings.xml
        mvn versions:set versions:update-child-modules -s $GITHUB_WORKSPACE/settings.xml -DnewVersion=$APPLICATION_VERSION -DprocessAllModule
        jfrog rt mvn clean install
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to JFrog Artifactory
      if: github.event_name != 'pull_request'
      run: |
        jfrog rt mvn 'install -DskipTests=true -f pom.xml' --build-name=$APPLICATION_NAME --build-number=$APPLICATION_VERSION
        jfrog rt build-publish $APPLICATION_NAME $APPLICATION_VERSION